FROM debian:jessie

# install passenger
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7 \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends apt-transport-https ca-certificates \
	&& echo deb https://oss-binaries.phusionpassenger.com/apt/passenger jessie main > /etc/apt/sources.list.d/passenger.list \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends passenger \
	&& rm -r /var/lib/apt/lists/*

WORKDIR /app
ENV PATH /usr/local/node/bin:$PATH

# install node and node app
RUN NODE_VERSION=4.3.2 \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends wget \
	&& rm -r /var/lib/apt/lists/* \

	&& mkdir /usr/local/node \
	&& wget https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz -O - \
		| tar -xz -C /usr/local/node --strip-components 1 \

	&& wget https://github.com/phusion/passenger-nodejs-connect-demo/archive/master.tar.gz -O - \
		| tar -xz -C /app --strip-components 1 \

	&& apt-get purge -y --auto-remove wget \
	&& npm install

EXPOSE 3000
CMD ["passenger-start", "--app-type", "node", "--startup-file", "app.js", "--delay-on-graceful-stop", "5s", "--memory-limit", "500", "--max-requests", "1000", "--timestamp"]

COPY passenger-start /usr/local/bin/
COPY passenger-monitor.sh /usr/local/bin/passenger-monitor
